# Autogenerated with SMOP 
from smop.core import *
# DisambiguateCameraPose.m

    
@function
def DisambiguateCameraPose(Cset=None,Rset=None,Xset=None,*args,**kwargs):
    varargin = DisambiguateCameraPose.varargin
    nargin = DisambiguateCameraPose.nargin

    for i in arange(1,length(Cset)).reshape(-1):
        D=dot(Rset[i],(Xset[i].T - dot(Cset[i],ones(1,size(Xset[i],1)))))
# DisambiguateCameraPose.m:4
        n[i]=length(find(D[3,:] > logical_and(0,Xset[i](arange(),3).T) > 0))
# DisambiguateCameraPose.m:5
    
    maxn,maxi=max(n,nargout=2)
# DisambiguateCameraPose.m:8
    C=Cset[maxi]
# DisambiguateCameraPose.m:9
    R=Rset[maxi]
# DisambiguateCameraPose.m:10
    X=Xset[maxi]
# DisambiguateCameraPose.m:11