# Autogenerated with SMOP 
from smop.core import *
# Display3D.m

    
@function
def Display3D(Cset=None,Rset=None,X=None,*args,**kwargs):
    varargin = Display3D.varargin
    nargin = Display3D.nargin

    for i in arange(1,length(Cset)).reshape(-1):
        hold('on')
        DisplayCameraPlane(Cset[i],Rset[i],0.5)
    
    hold('on')
    plot3(X[:,1],X[:,2],X[:,3],'b.')
    axis('equal')