# Autogenerated with SMOP 
from smop.core import *
# ExtractCameraPose.m

    
@function
def ExtractCameraPose(E=None,*args,**kwargs):
    varargin = ExtractCameraPose.varargin
    nargin = ExtractCameraPose.nargin

    W=matlabarray(cat([0,- 1,0],[1,0,0],[0,0,1]))
# ExtractCameraPose.m:3
    U,D,V=svd(E,nargout=3)
# ExtractCameraPose.m:4
    R=dot(dot(U,W),V.T)
# ExtractCameraPose.m:5
    C=U[:,3]
# ExtractCameraPose.m:6
    if det(R) < 0:
        R=- R
# ExtractCameraPose.m:8
        C=- C
# ExtractCameraPose.m:9
    
    Rset[1]=R
# ExtractCameraPose.m:11
    Cset[1]=dot(- R.T,C)
# ExtractCameraPose.m:12
    R=dot(dot(U,W),V.T)
# ExtractCameraPose.m:14
    C=- U[:,3]
# ExtractCameraPose.m:15
    if det(R) < 0:
        R=- R
# ExtractCameraPose.m:17
        C=- C
# ExtractCameraPose.m:18
    
    Rset[2]=R
# ExtractCameraPose.m:20
    Cset[2]=dot(- R.T,C)
# ExtractCameraPose.m:21
    R=dot(dot(U,W.T),V.T)
# ExtractCameraPose.m:23
    C=U[:,3]
# ExtractCameraPose.m:24
    if det(R) < 0:
        R=- R
# ExtractCameraPose.m:26
        C=- C
# ExtractCameraPose.m:27
    
    Rset[3]=R
# ExtractCameraPose.m:29
    Cset[3]=dot(- R.T,C)
# ExtractCameraPose.m:30
    R=dot(dot(U,W.T),V.T)
# ExtractCameraPose.m:32
    C=- U[:,3]
# ExtractCameraPose.m:33
    if det(R) < 0:
        R=- R
# ExtractCameraPose.m:35
        C=- C
# ExtractCameraPose.m:36
    
    Rset[4]=R
# ExtractCameraPose.m:38
    Cset[4]=dot(- R.T,C)
# ExtractCameraPose.m:39