# Autogenerated with SMOP 
from smop.core import *
# Vec2Skew.m

    
@function
def Vec2Skew(v=None,*args,**kwargs):
    varargin = Vec2Skew.varargin
    nargin = Vec2Skew.nargin

    skew=matlabarray(cat([0,- v[3],v[2]],[v[3],0,- v[1]],[- v[2],v[1],0]))
# Vec2Skew.m:2