# Autogenerated with SMOP 
from smop.core import *
# EssentialMatrixFromFundamentalMatrix.m

    
@function
def EssentialMatrixFromFundamentalMatrix(F=None,K=None,*args,**kwargs):
    varargin = EssentialMatrixFromFundamentalMatrix.varargin
    nargin = EssentialMatrixFromFundamentalMatrix.nargin

    ## EssentialMatrixFromFundamentalMatrix
# Use the camera calibration matrix to esimate the Essential matrix
# Inputs:
#     K - size (3 x 3) camera calibration (intrinsics) matrix
#     F - size (3 x 3) fundamental matrix from EstimateFundamentalMatrix
# Outputs:
#     E - size (3 x 3) Essential matrix with singular values (1,1,0)
    
    E=dot(dot(K.T,F),K)
# EssentialMatrixFromFundamentalMatrix.m:10
    U,__,V=svd(E,nargout=3)
# EssentialMatrixFromFundamentalMatrix.m:11
    corrMatrix=matlabarray(cat([1,0,0],[0,1,0],[0,0,0]))
# EssentialMatrixFromFundamentalMatrix.m:12
    E=dot(dot(U,corrMatrix),V.T)
# EssentialMatrixFromFundamentalMatrix.m:13